default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  adapter: postgresql
  database: UATech-rails-test_development
  username: michail

test:
  adapter: postgresql
  database: UATech-rails-test_test
  username: michail

production:
  adapter: postgresql
  database: UATech-rails-test_production
  username: rastu
  password: <%= ENV['RASTU_DATABASE_PASSWORD'] %>
